# Generated by Django 5.0.2 on 2024-02-14 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patron',
            old_name='name',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='name',
        ),
        migrations.RemoveField(
            model_name='librarian',
            name='name',
        ),
    ]
