# Generated by Django 5.0.2 on 2024-02-14 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_name_patron_password_remove_admin_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='date_published',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
    ]
