# Generated by Django 5.0.2 on 2024-02-28 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_user_alter_admin_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admin',
            table='Admin',
        ),
        migrations.AlterModelTable(
            name='book',
            table='Book',
        ),
        migrations.AlterModelTable(
            name='librarian',
            table='Librarian',
        ),
        migrations.AlterModelTable(
            name='patron',
            table='Patron',
        ),
    ]
