# Generated by Django 5.0.2 on 2024-04-15 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_admin_table_alter_book_table_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fee",
            fields=[
                ("fee_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "fee_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "Fee",
                "managed": False,
            },
        ),
    ]
