# Generated by Django 5.0.2 on 2024-04-15 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_fee"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"managed": True},
        ),
    ]
